[Thiago] FEAT: Cria schemas para validar entrada de dados
DEVin-ConectaNuvem/M2P2-DEVinventory-Squad2 pull request #16
Opened 2022-08-19 04:03 UTC by ThiagoW21

2022-08-19 19:53 UTC, MCoelho222 requested changes

2022-08-19 19:53 UTC, MCoelho222 commented on src/app/schemas/product_schema.py
> +    product_code = fields.Integer(required=True, error_messages=handle_error_messages('product_code'))
no body, não passaremos os id's. Passaremos, por exemplo, a categoria do produto, que será uma string

2022-08-19 19:53 UTC, MCoelho222 commented on src/app/schemas/user_schemas.py
> +
Corrigir a mensagem de erro, deve ser: A senha precisa ser maior ou igual a 8

2022-08-19 19:53 UTC, MCoelho222 commented on src/app/schemas/user_schemas.py
> +    name = fields.Str(required=True, error_messages=handle_error_messages('name'))
Mesmo comentário anterior sobre os id's

2022-08-19 19:53 UTC, MCoelho222 commented on src/app/schemas/user_schemas.py
> +    phone = fields.Str(required=True, error_messages=handle_error_messages('email'))
está "email" dentro da handle de phone

2022-08-19 19:53 UTC, MCoelho222 commented on src/app/utils/product_schema.py
> +    user_id = fields.Integer()
Entraremos com nomes no body, em vez de id's

2022-08-19 22:11 UTC, ViniciusPosssatto approved these changes

2022-08-19 22:11 UTC, VinehPS commented on src/app/schemas/user_schemas.py
> +
* 8 caracteres.

2022-08-19 23:34 UTC, MCoelho222 approved these changes

2022-08-19 23:35 UTC, Breno-MT requested changes
Fazer as questões lógicas nos schemas com validações

2022-08-20 00:02 UTC, Breno-MT approved these changes

2022-08-20 00:03 UTC, merged