[RAFAEL]feature/endpoint7-post-inventory
DEVin-ConectaNuvem/M2P2-DEVinventory-Squad2 pull request #18
Opened 2022-08-19 17:09 UTC by rafatellescarneiro

Criado a endpoint post inventory, com seus body parameters, seguido como orientado no card, para somente se o usuário tiver permissão WRITE. Se o product_code já exisitir no banco, retorna uma mensagem de erro (400), informando que o mesmo já existe. Se o value for menor ou igual a zero, retorna um erro informando que o valor não pode ser menor ou igual a zero. Ao criar o produto, retornaa mensagem de criado com sucesso(201)

Criado na services o inventory_services para a criação dos produtos.

Criado na utils exist_product_code para checar se o código do produto já existe no banco.

2022-08-19 18:49 UTC, MCoelho222 requested changes

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
>  from src.app.models.inventory import Inventory, intentories_share_schema
Precisa fazer alterações para não pedir product_category_id, e sim product_category apenas. Vou colocar sugestão de código. Aqui precisa importar:

`from src.app.models.product_category import ProductCategory, product_share_schema`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +    list_keys = ["product_category_id", "product_code", "title", "value", "brand", "template", "description"]
Trocar list_keys por:

`list_keys = ["product_category", "product_code", "title", "value", "brand", "template", "description"]`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +    if exist_product_code('data', 'product_code'):
Este if está recebendo duas strings, substituir por:

`if exist_product_code(data, inventory):`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +
Caso o data retorne error, vai dar um problema key error na função exist_product_code(), inserir:

`if 'error' in data:
        return {"error": data}, 401`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +
Definir os argumentos de exist_product_code, assim:

`inv_query = Inventory.query.all()
inventory = intentories_share_schema.dump(inv_query)`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +
são duas linhas ali em cima, está parecendo uma só...

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +
If data["user_id"] vai dar key error, porque essa chave não existe. Substituir por:

`if "user_id" not in data.keys():`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +        desription = data["description"]
Trocar desription por `description`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +
Aqui fazer a query para consultar o id:

`prod_cat_query = ProductCategory.query.filter_by(description=data['product_category']).first_or_404()
prod_cat_dict = product_share_schema.dump(prod_cat_query)`

2022-08-19 18:49 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +        product_category_id = data["product_category_id"],
trocar por:

`product_category_id = prod_cat_dict["id"],`

2022-08-19 20:24 UTC, Breno-MT commented
Resolvi os conflitos de arquivo que o GitHub avisou, nenhuma interferência nos arquivos e código, apenas ele não entender que a função criada era só mais uma, ta tudo tranquilo agora. Caso queiram fazer testes, não esqueçam de dar `git pull` na branch.

2022-08-19 23:59 UTC, rafatellescarneiro commented on src/app/controllers/inventories.py
>  from src.app.models.inventory import Inventory, intentories_share_schema
feito Marcelão

2022-08-19 23:59 UTC, rafatellescarneiro commented on src/app/controllers/inventories.py
> +    list_keys = ["product_category_id", "product_code", "title", "value", "brand", "template", "description"]
feito Marcelão(2)

2022-08-20 00:03 UTC, MCoelho222 approved these changes

2022-08-20 00:05 UTC, MCoelho222 approved these changes

2022-08-20 00:06 UTC, MCoelho222 approved these changes

2022-08-20 00:06 UTC, MCoelho222 approved these changes

2022-08-20 00:12 UTC, MCoelho222 requested changes

2022-08-20 00:12 UTC, MCoelho222 commented on src/app/controllers/inventories.py
> +    if user_id not in data.keys():
trocar user_id por "user_id"

2022-08-20 00:12 UTC, MCoelho222 commented on src/app/controllers/inventories.py
precisa manter o data['user_id'] = None, só altera no if

2022-08-20 00:35 UTC, MCoelho222 requested changes

2022-08-20 00:35 UTC, MCoelho222 commented on src/app/controllers/inventories.py
Pode apagar linha 60 e 61

2022-08-20 00:35 UTC, MCoelho222 commented on src/app/controllers/inventories.py
Dentro da response, mudar prod_cat_dict["id"] por data["product_category_id"]

2022-08-20 01:00 UTC, MCoelho222 approved these changes

2022-08-20 01:01 UTC, merged